/**
 * AutoPay Payment Platform - Element Plus 图标配置
 * 
 * @author AutoPay Team
 * @since 1.0.0
 */

// 导入 Element Plus 的图标组件
import {
  // 基础图标
  HomeFilled,
  Setting,
  User,
  Search,
  Plus,
  Edit,
  Delete,
  View,
  Refresh,
  Download,
  Upload,
  Print,
  Calendar,
  Bell,
  HelpFilled,
  
  // 状态图标
  Check,
  Close,
  Warning,
  InfoFilled,
  SuccessFilled,
  CircleCheck,
  CircleClose,
  CirclePlus,
  CirclePlusFilled,
  Remove,
  RemoveFilled,
  CircleCheckFilled,
  CircleCloseFilled,
  
  // 箭头图标
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Top,
  Bottom,
  Back,
  Right,
  DArrowLeft,
  DArrowRight,
  ArrowLeftBold,
  ArrowRightBold,
  ArrowUpBold,
  ArrowDownBold,
  TopBold,
  BottomBold,
  
  // 编辑图标
  EditPen,
  EditPenFilled,
  Rank,
  SortDown,
  SortUp,
  Sort,
  
  // 文件图标
  Document,
  DocumentAdd,
  DocumentCopy,
  DocumentDelete,
  DocumentEdit,
  DocumentChecked,
  DocumentRemove,
  Files,
  Folder,
  FolderOpened,
  FolderAdd,
  FolderDelete,
  FolderRemove,
  FolderOpenedFilled,
  FolderFilled,
  
  // 媒体图标
  Picture,
  PictureRounded,
  PictureFilled,
  VideoCamera,
  VideoCameraFilled,
  VideoPlay,
  VideoPause,
  Headset,
  Mic,
  MicRounded,
  VideoRounded,
  Camera,
  CameraFilled,
  PictureRoundedFilled,
  VideoCameraRounded,
  VideoCameraFilled as VideoCameraRoundedFilled,
  CameraRounded,
  CameraRoundedFilled,
  
  // 位置图标
  Location,
  LocationInformation,
  LocationFilled,
  MapLocation,
  
  // 消息图标
  ChatDotRound,
  ChatSquare,
  ChatLineRound,
  ChatLineSquare,
  ChatRound,
  ChatRoundFilled,
  ChatSquareFilled,
  Message,
  MessageBox,
  Postcard,
  Promotion,
  
  // 用户图标
  UserFilled,
  Avatar,
  Male,
  Female,
  Coordinate,
  UserFilled as AvatarFilled,
  
  // 购物图标
  ShoppingCart,
  ShoppingCartFull,
  ShoppingBag,
  ShoppingBagFull,
  Shop,
  PriceTag,
  PriceTags,
  
  // 数据图标
  PieChart,
  PieChartRounded,
  Odometer,
  DataLine,
  DataAnalysis,
  Histogram,
  
  // 时间图标
  Clock,
  Timer,
  CalendarMonth,
  CalendarWeek,
  CalendarDay,
  Clock100,
  Clock200,
  ClockTime,
  
  // 系统图标
  Monitor,
  Mobile,
  Phone,
  Service,
  Iphone,
  Ipad,
  PlatformIphone,
  PlatformElm,
  Sort,
  Finished,
  DeleteFilled,
  SemiSelect,
  Select,
  Loading,
  
  // 网络图标
  Connection,
  Link,
  Unlink,
  Share,
  ShareIcon,
  
  // 其他图标
  Grid,
  Menu,
  GridRounded,
  Menu as GridPointer,
  MagicStick,
  Present,
  CreditCard,
  Wallet,
  BankCard,
  Money,
  Coins,
  PiggyBank,
  Goblet,
  GobletFull,
  GobletSquare,
  GobletSquareFull,
  Football,
  RugbyBall,
  Basketball,
  Trophy,
  TrophyBase,
  Medal,
  Crown,
  Medal as TrophyBaseFilled,
  MedalFilled as TrophyFilled,
  Medal as Flag,
  Flag,
  Flag as FlagFilled,
  TrophyBase as FlagFilled2,
  CrownFilled,
  MagicStick as Guide,
  Reading,
  ReadingLamp,
  Paperclip,
  TakeawayBox,
  Basket,
  Basketball as Ball,
  Boxing,
  Gamepad,
  GamepadRight,
  Chess,
  Medal as MedalOne,
  Cup,
  CupChocolate,
  CrownOne,
  CrownTwo,
  
  // 颜色图标
  MagicWand,
  Star,
  StarFilled,
  Heart,
  HeartFilled,
  Sunrise,
  Sunset,
  Cloudy,
  PartlyCloudy,
  Sunny,
  Moon,
  Lightning,
  Umbrella,
  Snow,
  Sun,
  Cloud,
  MoonNight,
  CloudAndSun,
  Rain,
  Pouring,
  HeavyRain,
  LightRain,
  SunriseIcon,
  SunsetIcon,
  CloudyIcon,
  partlyCloudyIcon,
  sunnyIcon,
  moonIcon,
  lightningIcon,
  umbrellaIcon,
  snowIcon,
  sunIcon,
  cloudIcon,
  moonNightIcon,
  cloudAndSunIcon,
  rainIcon,
  pouringIcon,
  heavyRainIcon,
  lightRainIcon,
  
  // 工具图标
  Wrench,
  Tool,
  Setting as SettingRounded,
  CPU,
  Motherboard,
  HardDrive,
  Monitor as MonitorRounded,
  Mobile as PhoneIphone,
  Router,
  NetworkRadar,
  NetworkSocket,
  Bluetooth,
  Wifi,
  WifiRadar,
  Signal,
  Key,
  Lock,
  Unlock,
  Van,
  Truck,
  Motorcycle,
  Ship,
  Train,
  Bus,
  Bicycle,
  Trolleybus,
  Trailer,
  Metro,
  Truck as VanDelivery,
  Notebook,
  Notebook2,
  Folder as OfficeBuilding,
  Files as OfficeBuildingFilled,
  Notebook as School,
  Collection,
  Tickets,
  Ticket,
  Collection as OfficeBuilding as SchoolFilled,
  Collection as SchoolTwo,
  OfficeBuilding as SchoolThree,
  Notebooks,
  Book,
  Books,
  Book as BookFold,
  BookOpened,
  BookRead,
  BookMark,
  Book as BookOne,
  BookOpen as BookTwo,
  Books as BookThree,
  Collection as CollectionTag,
  Notebooks as NotebookOne,
  Notebook2 as NotebookTwo,
  Collection as CollectionOne,
  Tickets as CollectionTwo,
  Collection as CollectionThree,
  Notebooks as CollectionFour,
  Books as CollectionFive,
  Collection as Office as GuideIcon,
  Collection as CollectionTag as FlagOne,
  Office as OfficeBuilding as FlagTwo,
  Collection as School as FlagThree,
  Collection as SchoolTwo as FlagFour,
  OfficeBuilding as School as FlagFive,
  Collection as SchoolThree as FlagSix,
  Notebooks as SchoolFilled as FlagSeven,
  Books as CollectionTag as FlagEight,
  Collection as OfficeBuilding as SchoolFilled as FlagNine,
  
  // 网络图标
  Internet,
  Iphone as Phone as More,
  Iphone as Iphone as Phone as MoreFilled,
  
  // 手机相关
  Iphone as More as MoreIcon,
  Iphone as MoreFilled as MoreIconFilled,
  
  // 钱包相关
  Wallet as WalletIcon,
  BankCard as CreditCard as WalletIconFilled,
  Money as Wallet as WalletIcon as WalletIconTwo,
  Coins as Wallet as WalletIcon as WalletIconThree,
  PiggyBank as Wallet as WalletIcon as WalletIconFour,
  
  // 支付相关
  CreditCard as PaymentCard,
  Money as Cash,
  Wallet as DigitalWallet,
  BankCard as BankCardIcon,
  
  // 统计图表
  TrendCharts,
  DataAnalysis as Analytics,
  PieChart as ChartPie,
  Histogram as ChartHistogram,
  DataLine as ChartLine,
  Odometer as ChartGauge,
  TrendCharts as TrendChartIcon,
  
  // 状态指示
  TrendCharts as StatusIcon,
  DataAnalysis as PerformanceIcon,
  PieChart as DistributionIcon,
  Histogram as TrafficIcon,
  DataLine as TrendIcon,
  Odometer as MetricsIcon,
  
  // 安全相关
  Lock as SecurityLock,
  Key as SecurityKey,
  Lock as SecurityShield,
  SecurityLock as SecurityCertificate,
  Key as SecurityPassword,
  Lock as SecurityEncryption,
  
  // 通知相关
  Bell as NotificationBell,
  BellFilled as NotificationActive,
  Message as NotificationMessage,
  NotificationBell as NotificationAlert,
  BellFilled as NotificationWarning,
  Bell as NotificationInfo,
  BellFilled as NotificationSuccess,
  
  // 操作相关
  Refresh as RefreshIcon,
  Sync as SyncIcon,
  Loading as LoadingIcon,
  Setting as SettingsIcon,
  Search as SearchIcon,
  Filter as FilterIcon,
  Sort as SortIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  
  // 文件相关
  Files as FileList,
  Document as FileDocument,
  DocumentAdd as FileCreate,
  DocumentCopy as FileCopy,
  DocumentEdit as FileEdit,
  DocumentDelete as FileDelete,
  DocumentChecked as FileVerify,
  Folder as FileFolder,
  FolderOpened as FileFolderOpen,
  
  // 用户相关
  User as UserIcon,
  UserFilled as UserActive,
  Avatar as UserAvatar,
  Users as UserGroup,
  UserIcon as UserSingle,
  UserActive as UserOnline,
  UserAvatar as UserProfile,
  
  // 导航相关
  Menu as MenuIcon,
  Grid as GridIcon,
  Fold as FoldIcon,
  Expand as ExpandIcon,
  DArrowLeft as ArrowBack,
  DArrowRight as ArrowForward,
  
  // 支付渠道图标
  Wallet as AlipayIcon,
  CreditCard as WechatIcon,
  BankCard as UnionPayIcon,
  Wallet as CreditIcon,
  Money as CashIcon,
  
  // 业务相关
  ShoppingCart as OrderIcon,
  Shop as StoreIcon,
  PriceTag as ProductIcon,
  TrendCharts as SalesIcon,
  DataAnalysis as ReportIcon,
  Odometer as RevenueIcon,
  
  // 工具栏图标
  Printer as PrintIcon,
  Calendar as DateIcon,
  Clock as TimeIcon,
  Coordinate as LocationIcon,
  Phone as ContactIcon,
  Laptop as DeviceIcon,
  Share as ShareIcon,
  Link as ConnectionIcon,
  
  // 表单图标
  EditPen as EditIcon,
  Delete as DeleteIcon,
  Check as ConfirmIcon,
  Close as CancelIcon,
  Plus as AddIcon,
  Remove as RemoveIcon,
  
  // 弹窗图标
  Warning as WarningIcon,
  InfoFilled as InfoIcon,
  SuccessFilled as SuccessIcon,
  CircleCloseFilled as ErrorIcon,
  
  // 权限相关
  Lock as PermissionLock,
  UserFilled as PermissionUser,
  Setting as PermissionConfig,
  UserGroup as PermissionGroup
} from '@element-plus/icons-vue'

// 创建图标映射对象
export const elementIcons = {
  // 基础图标
  Home: HomeFilled,
  Setting: Setting,
  User: User,
  Search: Search,
  Plus: Plus,
  Edit: Edit,
  Delete: Delete,
  View: View,
  Refresh: Refresh,
  Download: Download,
  Upload: Upload,
  Print: Print,
  Calendar: Calendar,
  Bell: Bell,
  Help: HelpFilled,
  
  // 状态图标
  Check: Check,
  Close: Close,
  Warning: Warning,
  Info: InfoFilled,
  Success: SuccessFilled,
  CircleCheck: CircleCheck,
  CircleClose: CircleClose,
  CirclePlus: CirclePlus,
  CirclePlusFilled: CirclePlusFilled,
  Remove: Remove,
  RemoveFilled: RemoveFilled,
  CircleCheckFilled: CircleCheckFilled,
  CircleCloseFilled: CircleCloseFilled,
  
  // 箭头图标
  ArrowUp: ArrowUp,
  ArrowDown: ArrowDown,
  ArrowLeft: ArrowLeft,
  ArrowRight: ArrowRight,
  Top: Top,
  Bottom: Bottom,
  Back: Back,
  Right: Right,
  DArrowLeft: DArrowLeft,
  DArrowRight: DArrowRight,
  ArrowLeftBold: ArrowLeftBold,
  ArrowRightBold: ArrowRightBold,
  ArrowUpBold: ArrowUpBold,
  ArrowDownBold: ArrowDownBold,
  TopBold: TopBold,
  BottomBold: BottomBold,
  
  // 编辑图标
  EditPen: EditPen,
  EditPenFilled: EditPenFilled,
  Rank: Rank,
  SortDown: SortDown,
  SortUp: SortUp,
  Sort: Sort,
  
  // 文件图标
  Document: Document,
  DocumentAdd: DocumentAdd,
  DocumentCopy: DocumentCopy,
  DocumentDelete: DocumentDelete,
  DocumentEdit: DocumentEdit,
  DocumentChecked: DocumentChecked,
  DocumentRemove: DocumentRemove,
  Files: Files,
  Folder: Folder,
  FolderOpened: FolderOpened,
  FolderAdd: FolderAdd,
  FolderDelete: FolderDelete,
  FolderRemove: FolderRemove,
  FolderOpenedFilled: FolderOpenedFilled,
  FolderFilled: FolderFilled,
  
  // 媒体图标
  Picture: Picture,
  PictureRounded: PictureRounded,
  PictureFilled: PictureFilled,
  VideoCamera: VideoCamera,
  VideoCameraFilled: VideoCameraFilled,
  VideoPlay: VideoPlay,
  VideoPause: VideoPause,
  Headset: Headset,
  Mic: Mic,
  MicRounded: MicRounded,
  VideoRounded: VideoRounded,
  Camera: Camera,
  CameraFilled: CameraFilled,
  PictureRoundedFilled: PictureRoundedFilled,
  VideoCameraRounded: VideoCameraRounded,
  VideoCameraRoundedFilled: VideoCameraRoundedFilled,
  CameraRounded: CameraRounded,
  CameraRoundedFilled: CameraRoundedFilled,
  
  // 位置图标
  Location: Location,
  LocationInformation: LocationInformation,
  LocationFilled: LocationFilled,
  MapLocation: MapLocation,
  
  // 消息图标
  ChatDotRound: ChatDotRound,
  ChatSquare: ChatSquare,
  ChatLineRound: ChatLineRound,
  ChatLineSquare: ChatLineSquare,
  ChatRound: ChatRound,
  ChatRoundFilled: ChatRoundFilled,
  ChatSquareFilled: ChatSquareFilled,
  Message: Message,
  MessageBox: MessageBox,
  Postcard: Postcard,
  Promotion: Promotion,
  
  // 用户图标
  UserFilled: UserFilled,
  Avatar: Avatar,
  Male: Male,
  Female: Female,
  Coordinate: Coordinate,
  AvatarFilled: UserFilled,
  
  // 购物图标
  ShoppingCart: ShoppingCart,
  ShoppingCartFull: ShoppingCartFull,
  ShoppingBag: ShoppingBag,
  ShoppingBagFull: ShoppingBagFull,
  Shop: Shop,
  PriceTag: PriceTag,
  PriceTags: PriceTags,
  
  // 数据图标
  PieChart: PieChart,
  PieChartRounded: PieChartRounded,
  Odometer: Odometer,
  DataLine: DataLine,
  DataAnalysis: DataAnalysis,
  Histogram: Histogram,
  
  // 时间图标
  Clock: Clock,
  Timer: Timer,
  CalendarMonth: CalendarMonth,
  CalendarWeek: CalendarWeek,
  CalendarDay: CalendarDay,
  Clock100: Clock100,
  Clock200: Clock200,
  ClockTime: ClockTime,
  
  // 系统图标
  Monitor: Monitor,
  Mobile: Mobile,
  Phone: Phone,
  Service: Service,
  Iphone: Iphone,
  Ipad: Ipad,
  PlatformIphone: PlatformIphone,
  PlatformElm: PlatformElm,
  Sort: Sort,
  Finished: Finished,
  DeleteFilled: DeleteFilled,
  SemiSelect: SemiSelect,
  Select: Select,
  Loading: Loading,
  
  // 网络图标
  Connection: Connection,
  Link: Link,
  Unlink: Unlink,
  Share: Share,
  ShareIcon: ShareIcon,
  
  // 工具图标
  Wrench: Wrench,
  Tool: Tool,
  SettingRounded: Setting,
  CPU: CPU,
  Motherboard: Motherboard,
  HardDrive: HardDrive,
  MonitorRounded: Monitor,
  PhoneIphone: Mobile,
  Router: Router,
  NetworkRadar: NetworkRadar,
  NetworkSocket: NetworkSocket,
  Bluetooth: Bluetooth,
  Wifi: Wifi,
  WifiRadar: WifiRadar,
  Signal: Signal,
  Key: Key,
  Lock: Lock,
  Unlock: Unlock,
  
  // 其他图标
  Grid: Grid,
  Menu: Menu,
  GridRounded: GridRounded,
  GridPointer: Menu,
  MagicStick: MagicStick,
  Present: Present,
  CreditCard: CreditCard,
  Wallet: Wallet,
  BankCard: BankCard,
  Money: Money,
  Coins: Coins,
  PiggyBank: PiggyBank,
  
  // 支付相关图标
  PaymentCard: CreditCard,
  Cash: Money,
  DigitalWallet: Wallet,
  BankCardIcon: BankCard,
  
  // 统计图表
  ChartPie: PieChart,
  ChartHistogram: Histogram,
  ChartLine: DataLine,
  ChartGauge: Odometer,
  TrendChartIcon: TrendCharts,
  
  // 权限图标
  PermissionLock: Lock,
  PermissionUser: UserFilled,
  PermissionConfig: Setting,
  PermissionGroup: UserFilled
}

// 导出图标映射对象
export default elementIcons

// 导出所有图标组件（用于全局注册）
export const allIcons = {
  HomeFilled,
  Setting,
  User,
  Search,
  Plus,
  Edit,
  Delete,
  View,
  Refresh,
  Download,
  Upload,
  Print,
  Calendar,
  Bell,
  HelpFilled,
  Check,
  Close,
  Warning,
  InfoFilled,
  SuccessFilled,
  CircleCheck,
  CircleClose,
  CirclePlus,
  CirclePlusFilled,
  Remove,
  RemoveFilled,
  CircleCheckFilled,
  CircleCloseFilled,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Top,
  Bottom,
  Back,
  Right,
  DArrowLeft,
  DArrowRight,
  ArrowLeftBold,
  ArrowRightBold,
  ArrowUpBold,
  ArrowDownBold,
  TopBold,
  BottomBold,
  EditPen,
  EditPenFilled,
  Rank,
  SortDown,
  SortUp,
  Sort,
  Document,
  DocumentAdd,
  DocumentCopy,
  DocumentDelete,
  DocumentEdit,
  DocumentChecked,
  DocumentRemove,
  Files,
  Folder,
  FolderOpened,
  FolderAdd,
  FolderDelete,
  FolderRemove,
  FolderOpenedFilled,
  FolderFilled,
  Picture,
  PictureRounded,
  PictureFilled,
  VideoCamera,
  VideoCameraFilled,
  VideoPlay,
  VideoPause,
  Headset,
  Mic,
  MicRounded,
  VideoRounded,
  Camera,
  CameraFilled,
  PictureRoundedFilled,
  VideoCameraRounded,
  VideoCameraRoundedFilled,
  CameraRounded,
  CameraRoundedFilled,
  Location,
  LocationInformation,
  LocationFilled,
  MapLocation,
  ChatDotRound,
  ChatSquare,
  ChatLineRound,
  ChatLineSquare,
  ChatRound,
  ChatRoundFilled,
  ChatSquareFilled,
  Message,
  MessageBox,
  Postcard,
  Promotion,
  UserFilled,
  Avatar,
  Male,
  Female,
  Coordinate,
  ShoppingCart,
  ShoppingCartFull,
  ShoppingBag,
  ShoppingBagFull,
  Shop,
  PriceTag,
  PriceTags,
  PieChart,
  PieChartRounded,
  Odometer,
  DataLine,
  DataAnalysis,
  Histogram,
  Clock,
  Timer,
  CalendarMonth,
  CalendarWeek,
  CalendarDay,
  Clock100,
  Clock200,
  ClockTime,
  Monitor,
  Mobile,
  Phone,
  Service,
  Iphone,
  Ipad,
  PlatformIphone,
  PlatformElm,
  Finished,
  DeleteFilled,
  SemiSelect,
  Select,
  Loading,
  Connection,
  Link,
  Unlink,
  Share,
  ShareIcon,
  Wrench,
  Tool,
  CPU,
  Motherboard,
  HardDrive,
  Router,
  NetworkRadar,
  NetworkSocket,
  Bluetooth,
  Wifi,
  WifiRadar,
  Signal,
  Key,
  Lock,
  Unlock,
  Grid,
  Menu,
  GridRounded,
  MagicStick,
  Present,
  CreditCard,
  Wallet,
  BankCard,
  Money,
  Coins,
  PiggyBank,
  Guide,
  Reading,
  ReadingLamp,
  Paperclip,
  TakeawayBox,
  Basket
}